id: IE81B484E
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:23:44.983560+00:00
last_modified: 2022-12-14 18:23:44.983566+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-088-038
  eft-text-version: 1.21.2 2020
  title: Toh_543-The_Root_Manual_of_the_Rites_of_Manjusri-v2
bases:
  '2205':
    source_metadata: null
    order: 1
    base_file: 2205.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
